import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {createTeamService} from '../server/team-api.js';
import {createAppServer} from '../server/index.js';
const hash=s=>createHash('sha256').update(s).digest('hex');
const board={schema:4,nodes:[],wires:[]};
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'schematica-team-'));const identities=join(dir,'identities.json');const users=[{id:'alice',name:'Alice',tokenHash:hash('a'.repeat(48))},{id:'bob',name:'Bob',tokenHash:hash('b'.repeat(48))}];await writeFile(identities,JSON.stringify({version:1,users}));let service=await createTeamService({directory:join(dir,'data'),identitiesFile:identities,root:process.cwd()});let server=createAppServer({teamService:service});await new Promise(r=>server.listen(0,'127.0.0.1',r));let base=`http://127.0.0.1:${server.address().port}`;const call=async(path='',body,token='a'.repeat(48),headers={})=>{const res=await fetch(base+'/api/team'+path,{method:body===undefined?'GET':'POST',headers:{'x-schematica-client':'1',authorization:'Bearer '+token,'content-type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:res.status,...await res.json()};};t.after(async()=>{await new Promise(r=>server.close(r));await service.close();await rm(dir,{recursive:true,force:true});});return {call,dir,identities,users,restart:async()=>{await new Promise(r=>server.close(r));await service.close();service=await createTeamService({directory:join(dir,'data'),identitiesFile:identities,root:process.cwd()});server=createAppServer({teamService:service});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;}};}
test('HTTP membership, discussion, immutable approval, concurrent versions, restart and revocation',async t=>{const f=await fixture(t);const {call}=f;assert.equal((await call('/me',undefined,'wrong')).status,401);assert.equal((await call('/me',undefined,undefined,{origin:'https://evil.example'})).status,403);let r=await call('/projects',{title:'Design',board});assert.equal(r.status,200);let p=r.project;const path='/projects/'+p.id;assert.equal((await call(path,undefined,'b'.repeat(48))).status,404);p=(await call(path+'/members',{version:p.version,userId:'bob',role:'reviewer'})).project;assert.equal((await call(path+'/revisions',{version:p.version,board},'b'.repeat(48))).status,403);p=(await call(path+'/comments',{version:p.version,revisionId:p.latestRevisionId,text:'Fix this',target:'',author:{id:'alice'}},'b'.repeat(48))).project;assert.equal(p.comments[0].author.id,'bob');assert.equal((await call(path+'/reviews',{version:p.version,revisionId:p.latestRevisionId,status:'approved'})).status,409);p=(await call(path+'/comments/'+p.comments[0].id,{version:p.version,resolved:true})).project;p=(await call(path+'/reviews',{version:p.version,revisionId:p.latestRevisionId,status:'approved',comment:''})).project;const old=p.latestRevisionId;const concurrent=await Promise.all([call(path+'/revisions',{version:p.version,board}),call(path+'/revisions',{version:p.version,board})]);assert.deepEqual(concurrent.map(x=>x.status).sort(),[200,409]);p=concurrent.find(x=>x.status===200).project;assert.equal(p.reviews[0].revisionId,old);assert.equal((await call(path+'/reviews',{version:p.version,revisionId:old,status:'approved'})).status,409);await f.restart();assert.deepEqual((await call(path)).project,p);assert.equal((await call(path+'/export')).status,200);await writeFile(f.identities,JSON.stringify({version:1,users:f.users.map(u=>({...u,disabled:u.id==='bob'}))}));assert.equal((await call('/me',undefined,'b'.repeat(48))).status,401);});
test('directory locking, validation and failed persistence preserve state',async t=>{const f=await fixture(t);await assert.rejects(createTeamService({directory:join(f.dir,'data'),identitiesFile:f.identities,root:process.cwd()}));assert.equal((await f.call('/projects',{title:'bad',board:{nodes:'bad'}})).status,400);assert.equal((await f.call('/projects',{title:'x'.repeat(201),board})).status,400);const p=(await f.call('/projects',{title:'ok',board})).project;const {rename,mkdir}=await import('node:fs/promises');const data=join(f.dir,'data');await rename(data,data+'-away');await writeFile(data,'blocked');assert.equal((await f.call('/projects/'+p.id+'/comments',{version:p.version,revisionId:p.latestRevisionId,text:'not persisted'})).status,500);assert.deepEqual((await f.call('/projects/'+p.id)).project,p);await rm(data);await rename(data+'-away',data);await mkdir(join(data,'unused'));});
test('disabled service exposes status only',async t=>{const server=createAppServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base=`http://127.0.0.1:${server.address().port}`;assert.deepEqual(await (await fetch(base+'/api/team/status')).json(),{enabled:false});assert.equal((await fetch(base+'/api/team/me')).status,404);});
test('caps, invalid path, membership removal and invalid identity fail closed',async t=>{const f=await fixture(t);assert.equal((await f.call('/projects/../../server/index.js')).status,404);assert.equal((await f.call('/projects',{title:'large',board:{...board,title:'x'.repeat(17*1024*1024)}})).status,413);let p=(await f.call('/projects',{title:'scope',board})).project;const path='/projects/'+p.id;p=(await f.call(path+'/members',{version:p.version,userId:'bob',role:'editor'})).project;assert.equal((await f.call(path+'/members',{version:p.version,userId:'alice',role:null},'b'.repeat(48))).status,403);p=(await f.call(path+'/members',{version:p.version,userId:'bob',role:null})).project;assert.equal((await f.call(path,undefined,'b'.repeat(48))).status,404);await writeFile(f.identities,'invalid');assert.equal((await f.call('/me')).status,503);});
for (const identityState of ['disabled', 'missing']) {
 test(`owner removes ${identityState} identity membership before identity is restored`, async t => {
  const f = await fixture(t);
  let p = (await f.call('/projects', {title: 'Revocation', board})).project;
  const path = '/projects/' + p.id;
  p = (await f.call(path + '/members', {version: p.version, userId: 'bob', role: 'editor'})).project;
  const users = identityState === 'disabled'
   ? f.users.map(user => ({...user, disabled: user.id === 'bob'}))
   : f.users.filter(user => user.id !== 'bob');
  await writeFile(f.identities, JSON.stringify({version: 1, users}));

  assert.equal((await f.call(path + '/members', {version: p.version, userId: 'alice', role: null})).status, 400);
  assert.equal((await f.call(path + '/members', {version: p.version, userId: 'bob', role: 'reviewer'})).status, 400);
  const removed = await f.call(path + '/members', {version: p.version, userId: 'bob', role: null});
  assert.equal(removed.status, 200);
  assert.equal(Object.hasOwn(removed.project.members, 'bob'), false);
  assert.equal(removed.project.version, p.version + 1);

  await f.restart();
  await writeFile(f.identities, JSON.stringify({version: 1, users: f.users}));
  assert.equal((await f.call('/me', undefined, 'b'.repeat(48))).status, 200);
  assert.equal((await f.call(path, undefined, 'b'.repeat(48))).status, 404);
  assert.deepEqual((await f.call('/projects', undefined, 'b'.repeat(48))).projects, []);
  assert.equal((await f.call(path + '/comments', {
   version: removed.project.version,
   revisionId: removed.project.latestRevisionId,
   text: 'Access must remain revoked',
  }, 'b'.repeat(48))).status, 404);
 });
}
test('private configuration is refused inside repository',async()=>{await assert.rejects(createTeamService({directory:process.cwd(),identitiesFile:join(process.cwd(),'package.json'),root:process.cwd()}),/outside/);});
test('restart refuses damaged snapshot identity and releases acquired lock',async t=>{const dir=await mkdtemp(join(tmpdir(),'schematica-corrupt-'));t.after(()=>rm(dir,{recursive:true,force:true}));const identities=join(dir,'identities.json'),data=join(dir,'data');await writeFile(identities,JSON.stringify({version:1,users:[]}));const service=await createTeamService({directory:data,identitiesFile:identities,root:process.cwd()});await Promise.all([service.close(),service.close()]);await writeFile(join(data,'projects.json'),JSON.stringify({version:1,projects:[{id:'bad'}]}));await assert.rejects(createTeamService({directory:data,identitiesFile:identities,root:process.cwd()}));await rm(join(data,'projects.json'));const replacement=await createTeamService({directory:data,identitiesFile:identities,root:process.cwd()});await replacement.close();});
test('concurrent body uploads are bounded before mutation queue',async t=>{const {request}=await import('node:http');const dir=await mkdtemp(join(tmpdir(),'schematica-upload-'));const identities=join(dir,'identities.json');await writeFile(identities,JSON.stringify({version:1,users:[{id:'alice',name:'Alice',tokenHash:hash('a'.repeat(48))}]}));const service=await createTeamService({directory:join(dir,'data'),identitiesFile:identities,root:process.cwd()});const server=createAppServer({teamService:service});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const uploads=[];t.after(async()=>{uploads.forEach(r=>r.destroy());server.closeAllConnections();await new Promise(r=>server.close(r));await service.close();await rm(dir,{recursive:true,force:true});});for(let i=0;i<16;i++){const req=request(base+'/api/team/projects',{method:'POST',headers:{'x-schematica-client':'1',authorization:'Bearer '+'a'.repeat(48),'content-type':'application/json'}},()=>{});req.on('error',()=>{});req.write('{');uploads.push(req);}await new Promise(r=>setTimeout(r,50));const res=await fetch(base+'/api/team/me',{headers:{'x-schematica-client':'1',authorization:'Bearer '+'a'.repeat(48)}});assert.equal(res.status,429);});
test('operator provisioning writes hashed config and exclusive private credential file',async t=>{const {provisionTeamIdentity}=await import('../server/team-provision.js');const {readFile,stat}=await import('node:fs/promises');const dir=await mkdtemp(join(tmpdir(),'schematica-provision-'));t.after(()=>rm(dir,{recursive:true,force:true}));const identitiesFile=join(dir,'identities.json'),credentialFile=join(dir,'credential');const options={identitiesFile,credentialFile,id:'operator',name:'Operator',root:process.cwd()};await provisionTeamIdentity(options);const token=(await readFile(credentialFile,'utf8')).trim();const config=JSON.parse(await readFile(identitiesFile,'utf8'));assert.equal(config.users[0].tokenHash,hash(token));assert.equal(JSON.stringify(config).includes(token),false);assert.equal((await stat(credentialFile)).mode&0o777,0o600);await assert.rejects(provisionTeamIdentity(options));assert.equal((await readFile(credentialFile,'utf8')).trim(),token);});
