import {readFile,stat} from 'node:fs/promises';
import {createHash,randomUUID,timingSafeEqual} from 'node:crypto';
import {reviewSnapshot} from '../src/review-snapshot.js';
import {createTeamStore,privatePath,teamError} from './team-store.js';
const MAX_BODY=17*1024*1024;
const digest=value=>createHash('sha256').update(value).digest('hex');
const object=value=>value&&typeof value==='object'&&!Array.isArray(value);
function text(value,max,optional=false){if(optional&&(value===undefined||value===''))return undefined;if(typeof value!=='string'||!value.trim()||value.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))throw teamError(400,'Invalid text field.');return value.trim();}
export async function readTeamIdentities(file){if((await stat(file)).size>1024*1024)throw Error('Invalid identity configuration.');const config=JSON.parse(await readFile(file,'utf8'));const ids=new Set(),hashes=new Set();if(config?.version!==1||!Array.isArray(config.users)||config.users.length>1000)throw Error('Invalid identity configuration.');for(const u of config.users){if(!object(u)||typeof u.id!=='string'||! /^[A-Za-z0-9_-]{1,80}$/.test(u.id)||u.id==='__proto__'||u.id==='constructor'||u.id==='prototype'||typeof u.name!=='string'||!u.name.trim()||u.name.length>200||! /^[a-f0-9]{64}$/.test(u.tokenHash)||ids.has(u.id)||hashes.has(u.tokenHash)||(u.disabled!==undefined&&typeof u.disabled!=='boolean'))throw Error('Invalid identity configuration.');ids.add(u.id);hashes.add(u.tokenHash);}return config.users;}
function snapshot(board){if(!object(board)||!Array.isArray(board.nodes)||!Array.isArray(board.wires)||board.nodes.length>5000||board.wires.length>20000||['zones','notes','journey'].some(k=>board[k]!==undefined&&(!Array.isArray(board[k])||board[k].length>10000)))throw teamError(400,'A supported Schematica board is required.');try{const result=reviewSnapshot(board);return {board:result.board,hash:digest(result.canonical)};}catch{throw teamError(400,'Invalid board. Repair it before publishing.');}}
function body(req){return new Promise((resolve,reject)=>{let bytes=0;const chunks=[];const timer=setTimeout(()=>fail(teamError(408,'Team request timed out.')),10000);const cleanup=()=>{clearTimeout(timer);req.off('data',data);req.off('end',end);req.off('error',fail);req.off('aborted',aborted);};const fail=e=>{cleanup();req.resume();reject(e);};const aborted=()=>fail(teamError(400,'Team request interrupted.'));const data=chunk=>{bytes+=chunk.length;if(bytes>MAX_BODY)return fail(teamError(413,'Team request is too large.'));chunks.push(chunk);};const end=()=>{cleanup();try{const value=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!object(value))throw Error();resolve(value);}catch{reject(teamError(400,'Use a JSON object.'));}};if(Number(req.headers['content-length'])>MAX_BODY)return fail(teamError(413,'Team request is too large.'));req.on('data',data);req.on('end',end);req.on('error',fail);req.on('aborted',aborted);});}
function validateStored(state){
 const uuid=value=>typeof value==='string'&&/^[a-f0-9-]{36}$/.test(value);
 const unique=items=>new Set(items.map(v=>v.id)).size===items.length;
 const actor=value=>object(value)&&typeof value.id==='string'&&typeof value.name==='string';
 if(state.projects.length>100||!unique(state.projects))throw Error('Invalid team storage.');
 for(const p of state.projects){
  if(!object(p)||!uuid(p.id)||typeof p.title!=='string'||p.title.length>200||!Number.isSafeInteger(p.version)||p.version<1||!object(p.members)||p.members[p.owner]!=='editor'||Object.values(p.members).some(r=>!['editor','reviewer'].includes(r))||!Array.isArray(p.revisions)||!p.revisions.length||p.revisions.length>100||!Array.isArray(p.comments)||p.comments.length>1000||!Array.isArray(p.reviews)||p.reviews.length>1000||!unique(p.revisions)||!unique(p.comments)||!unique(p.reviews)||p.latestRevisionId!==p.revisions.at(-1).id)throw Error('Invalid team storage.');
  for(const r of p.revisions)if(!uuid(r.id)||!actor(r.author)||typeof r.title!=='string'||r.hash!==snapshot(r.board).hash)throw Error('Invalid revision storage.');
  for(const c of p.comments)if(!uuid(c.id)||!actor(c.author)||!p.revisions.some(r=>r.id===c.revisionId)||typeof c.text!=='string'||c.text.length>4000||typeof c.resolved!=='boolean')throw Error('Invalid comment storage.');
  for(const r of p.reviews)if(!uuid(r.id)||!actor(r.author)||!p.revisions.some(v=>v.id===r.revisionId&&v.hash===r.hash)||!['approved','changes-requested'].includes(r.status))throw Error('Invalid review storage.');
 }
}
export async function createTeamService({directory,identitiesFile,root}={}){
 if(!directory||!identitiesFile||!root)throw Error('Team directory, identity file and repository root are required.');
 directory=await privatePath(directory,root,{directory:true});identitiesFile=await privatePath(identitiesFile,root);await readTeamIdentities(identitiesFile);const store=await createTeamStore(directory,validateStored);let active=0;
 function project(state,id,user){const p=state.projects.find(p=>p.id===id);if(!p||!Object.hasOwn(p.members,user.id))throw teamError(404,'Project not found.');return p;}
 function revision(p,b,actor,title){if(p.revisions.length>=100)throw teamError(413,'Revision capacity reached.');const snap=snapshot(b);const r={id:randomUUID(),...snap,title,createdAt:new Date().toISOString(),author:actor};p.revisions.push(r);p.latestRevisionId=r.id;}
 return {close:()=>store.close(),async handle(req,res,url,origin){
 const send=value=>{res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(value));};
 if(url.pathname==='/api/team/status'&&req.method==='GET'){send({enabled:true});return;}
 if(active>=16)throw teamError(429,'Team service is busy.');active++;try{
 if(req.headers['x-schematica-client']!=='1'||(req.headers.origin&&req.headers.origin!==origin)||(req.headers['sec-fetch-site']&&req.headers['sec-fetch-site']!=='same-origin'))throw teamError(403,'Cross-origin team access is not enabled.');
 let users;try{await privatePath(identitiesFile,root);users=await readTeamIdentities(identitiesFile);}catch{throw teamError(503,'Team identity configuration is unavailable.');}
 const token=/^Bearer ([A-Za-z0-9_-]{32,256})$/.exec(req.headers.authorization||'')?.[1];const tokenHash=digest(token||'');const user=token&&users.find(u=>!u.disabled&&timingSafeEqual(Buffer.from(u.tokenHash,'hex'),Buffer.from(tokenHash,'hex')));if(!user)throw teamError(401,'A valid team credential is required.');const actor={id:user.id,name:user.name};
 const match=/^\/api\/team\/(me|projects)(?:\/([a-f0-9-]{36})(?:\/(revisions|members|comments|reviews|export)(?:\/([a-f0-9-]{36}))?)?)?$/.exec(url.pathname);if(!match)throw teamError(404,'Not found.');const [,resource,id,action,commentId]=match;
 if(req.method==='GET'){if(resource==='me'&&!id){send({user:actor});return;}if(resource!=='projects')throw teamError(404,'Not found.');const state=store.read();if(!id){send({projects:state.projects.filter(p=>Object.hasOwn(p.members,user.id)).map(p=>({id:p.id,title:p.title,version:p.version,latestRevisionId:p.latestRevisionId,role:p.members[user.id]}))});return;}const p=project(state,id,user);if(action==='export'&&!commentId){send({format:'schematica-team-review',version:1,project:p});return;}if(action)throw teamError(404,'Not found.');send({project:p});return;}
 if(req.method!=='POST')throw teamError(405,'Only GET and POST are supported.');if(!/^application\/json(?:;|$)/i.test(req.headers['content-type']||''))throw teamError(415,'Use application/json.');const input=await body(req);
 // Re-read identity after body upload, then authorize again inside the serialized mutation.
 const mutate=async()=>{try{await privatePath(identitiesFile,root);users=await readTeamIdentities(identitiesFile);}catch{throw teamError(503,'Team identity configuration is unavailable.');}if(!users.some(u=>u.id===user.id&&!u.disabled&&u.tokenHash===tokenHash))throw teamError(401,'A valid team credential is required.');return store.mutate(async state=>{
 let currentUsers;try{await privatePath(identitiesFile,root);currentUsers=await readTeamIdentities(identitiesFile);}catch{throw teamError(503,'Team identity configuration is unavailable.');}
 if(!currentUsers.some(u=>u.id===user.id&&!u.disabled&&u.tokenHash===tokenHash))throw teamError(401,'A valid team credential is required.');users=currentUsers;
 if(resource!=='projects')throw teamError(404,'Not found.');if(!id){if(action||state.projects.length>=100)throw teamError(413,'Project capacity reached.');const title=text(input.title,200);const p={id:randomUUID(),title,owner:user.id,version:1,members:{[user.id]:'editor'},latestRevisionId:null,revisions:[],comments:[],reviews:[]};revision(p,input.board,actor,title);state.projects.push(p);return p;}
 const p=project(state,id,user);if(!Number.isSafeInteger(input.version)||input.version!==p.version)throw teamError(409,'Project changed. Reload before saving.');
 if(action==='revisions'&&!commentId){if(p.members[user.id]!=='editor')throw teamError(403,'Editor membership is required.');const title=input.title===undefined?p.title:text(input.title,200);revision(p,input.board,actor,title);p.title=title;}
 else if(action==='members'&&!commentId){if(p.owner!==user.id)throw teamError(403,'Only the project owner can manage membership.');if(!['editor','reviewer',null].includes(input.role)||!users.some(u=>u.id===input.userId&&!u.disabled)||input.userId===p.owner)throw teamError(400,'Invalid membership.');if(input.role===null)delete p.members[input.userId];else p.members[input.userId]=input.role;}
 else if(action==='comments'&&!commentId){if(p.comments.length>=1000)throw teamError(413,'Comment capacity reached.');if(!p.revisions.some(r=>r.id===input.revisionId))throw teamError(400,'Unknown revision.');p.comments.push({id:randomUUID(),revisionId:input.revisionId,text:text(input.text,4000),target:text(input.target,200,true),createdAt:new Date().toISOString(),author:actor,resolved:false});}
 else if(action==='comments'&&commentId){const c=p.comments.find(c=>c.id===commentId);if(!c)throw teamError(404,'Comment not found.');if(typeof input.resolved!=='boolean')throw teamError(400,'Resolution must be boolean.');c.resolved=input.resolved;c.resolvedBy=actor;}
 else if(action==='reviews'&&!commentId){if(p.reviews.length>=1000)throw teamError(413,'Review capacity reached.');const r=p.revisions.find(r=>r.id===input.revisionId);if(!r||!['approved','changes-requested'].includes(input.status))throw teamError(400,'Invalid review.');if(input.status==='approved'&&(r.id!==p.latestRevisionId||p.comments.some(c=>c.revisionId===r.id&&!c.resolved)))throw teamError(409,'Approval requires the latest revision with resolved comments.');p.reviews.push({id:randomUUID(),revisionId:r.id,hash:r.hash,status:input.status,createdAt:new Date().toISOString(),author:actor,comment:text(input.comment,4000,true)});}
 else throw teamError(404,'Not found.');p.version++;return p;});};send({project:await mutate()});
 }finally{active--;}
 }};
}
