// Explanations accompany the actual catalogue badges, ports and field labels.
// Each entry is [English, Simplified Chinese].
export const PART_HELP = {
  mcu: ['A microcontroller runs firmware and coordinates sensors and outputs. Use it as the control hub, then choose ports matching each peripheral.', '微控制器运行固件并协调传感器与输出。将其作为控制中心，再选择与各外设匹配的端口。'],
  sbc: ['A system-on-chip or single-board computer represents the main application processor. Use it for operating systems, networking or higher-level processing; record the actual board model.', '片上系统或单板计算机代表主应用处理器。用于操作系统、网络或上层处理，并填写实际板卡型号。'],
  fpga: ['Programmable logic represents custom parallel processing or interface timing. Describe the logic function and declare the interfaces used by your design.', '可编程逻辑表示自定义并行处理或接口时序。说明逻辑功能，并声明设计使用的接口。'],
  dsp: ['A digital signal processor represents filtering, audio or other signal-processing work. Label the processing stage and connect its input and output paths.', '数字信号处理器表示滤波、音频等信号处理任务。标明处理阶段并连接输入、输出路径。'],
  temp: ['Measures temperature. Set the sensor model, address and supply rail, then connect its measurement bus and power.', '测量温度。填写传感器型号、地址和供电电压，再连接测量总线与电源。'],
  imu: ['An inertial measurement unit represents acceleration and rotation sensing. Record the actual axes or model and connect the selected data interface.', '惯性测量单元表示加速度与旋转测量。记录实际轴数或型号，并连接所选数据接口。'],
  gps: ['A positioning receiver provides location or timing information. Use it for GNSS/GPS input and label the receiver and host connection.', '定位接收器提供位置或时间信息。用于 GNSS/GPS 输入，并标明接收器及主机连接。'],
  camera: ['A general camera captures images. Use a MIPI or automotive camera tile when that more specific interface better describes your hardware.', '通用摄像头采集图像。若硬件使用更具体的接口，可改用 MIPI 或车载摄像头图块。'],
  adcin: ['Represents an analog measurement entering an ADC. Record the signal range and conditioning separately from the converter supply voltage.', '表示进入模数转换器的模拟测量信号。单独记录信号范围与调理电路，不要与转换器供电电压混淆。'],
  sensor: ['A general-purpose sensor placeholder. Rename it to the quantity measured and customize its ports when the built-in definition does not match.', '通用传感器占位符。按被测量命名；内置定义不符时，自定义端口。'],
  motor: ['Represents a motor together with its driver. Connect its control and power paths; use a separate motor-controller tile when the driver needs its own detail.', '表示电机及其驱动器。连接控制与供电路径；驱动器需要单独描述时，使用电机控制器图块。'],
  servo: ['Represents a position-controlled actuator with a control input. Record the servo model and power rail; use Serial servo for a bus-controlled chain.', '表示带控制输入的位置执行器。记录舵机型号与供电电压；总线级联设备可用串行舵机。'],
  relay: ['An electrically controlled switch. Show the control connection and describe the switched load and contact rating in its notes.', '电控开关。画出控制连接，并在备注中说明被切换负载与触点额定值。'],
  led: ['An indicator or lighting output. Name its purpose and document the driver or current limiting used in the real circuit.', '指示灯或照明输出。按用途命名，并记录实际电路使用的驱动或限流措施。'],
  display: ['A screen or visual output. Enter the display model and connect its host interface and supply.', '屏幕或视觉输出。填写显示器型号，连接主机接口与电源。'],
  buzzer: ['An audible alert output. Describe the alert and the control or driver needed to produce it.', '声音告警输出。描述告警用途及其控制、驱动方式。'],
  battery: ['Stored energy for a portable system. Enter capacity and output limits when known so declared power-budget estimates can use them.', '便携系统的储能部件。已知时填写容量与输出限制，供电源预算估算使用。'],
  regulator: ['Converts or stabilizes a supply rail. Distinguish input and output rails, and record current limits and conversion assumptions.', '转换或稳定供电电压。区分输入与输出电压，并记录电流限制及转换假设。'],
  charger: ['Represents battery charging circuitry. Show the incoming power and battery paths and document the supported battery chemistry.', '表示电池充电电路。画出输入电源和电池路径，并记录支持的电池化学体系。'],
  solar: ['A photovoltaic energy source. Connect it to the power-conversion or charging stage and record the operating conditions behind its rating.', '光伏能源。连接电源转换或充电阶段，并记录额定值对应的工作条件。'],
  jack: ['An external power input connector. Label polarity, input voltage and current rating before connecting the downstream rail.', '外部电源输入连接器。连接下游供电前，标明极性、输入电压与额定电流。'],
  wifi: ['Wireless local connectivity, including WiFi or Bluetooth. State the module and link purpose; the tile itself does not establish a network.', 'WiFi 或蓝牙等本地无线连接。说明模块与链路用途；图块本身不会建立网络。'],
  lora: ['A long-range radio module. Show its host and radio paths, and document frequency or regional constraints in notes.', '远距离无线模块。显示主机与射频路径，并在备注中记录频段或地区限制。'],
  cellular: ['A cellular modem for wide-area connectivity. Record the module, host bus and network role, including peak current if known.', '广域蜂窝通信调制解调器。记录模块、主机总线和网络角色，已知时填写峰值电流。'],
  ethphy: ['The physical Ethernet interface between a host and cable-side network. Distinguish this hardware block from a router or Ethernet switch.', '主机与有线网络之间的以太网物理接口。将此硬件模块与路由器、以太网交换机区分。'],
  usbport: ['A USB connector or interface boundary. Describe the connector, host/device role and any power-delivery assumptions.', 'USB 连接器或接口边界。说明连接器、主机或设备角色以及供电假设。'],
  cantrx: ['A CAN physical-layer transceiver between logic and the vehicle or device bus. Record the actual transceiver and supported bus requirements.', '逻辑端与车辆或设备总线之间的 CAN 物理层收发器。记录实际型号及支持的总线要求。'],
  antenna: ['An RF antenna or radio endpoint. Connect the RF path and document band, connector and placement assumptions.', '射频天线或无线端点。连接射频路径，并记录频段、连接器和布置假设。'],
  stepper: ['A stepper motor and driver for discrete motion. Document step/direction control, motor supply and drive-current settings.', '用于步进运动的电机与驱动器。记录步进、方向控制、电机供电与驱动电流设置。'],
  encoder: ['Position or rotation feedback. Connect its output to the controller and record the encoding method and resolution.', '位置或旋转反馈。将输出连接到控制器，并记录编码方式与分辨率。'],
  lidar: ['Laser ranging for distance or scene perception. Record the unit and data interface; show its processing destination.', '用于距离或场景感知的激光测距设备。记录型号与数据接口，并显示处理目标。'],
  ultrasonic: ['Acoustic distance sensing. Describe trigger and measurement signals and record the intended sensing range.', '声学测距设备。说明触发与测量信号，并记录预期检测范围。'],
  tof: ['A time-of-flight distance sensor. Use it for proximity or ranging and record the model, address and bus.', '飞行时间距离传感器。用于接近检测或测距，记录型号、地址与总线。'],
  limitswitch: ['A mechanical end-stop or limit input. State the normal contact condition and the controller input it drives.', '机械行程或限位输入。说明常态触点状态及其驱动的控制器输入。'],
  rdksoftware: ['A software stage in an RDK pipeline, such as capture, inference or post-processing. Describe the data passed between stages rather than treating it as a physical chip.', 'RDK 流水线的软件阶段，如采集、推理或后处理。说明阶段间传递的数据，不应将其视为实体芯片。'],
  aisbc: ['An AI development board or robot compute kit. Select the actual board model and verify peripheral compatibility against its documentation.', 'AI 开发板或机器人计算套件。选择实际板卡型号，并依据文档核对外设兼容性。'],
  mipicam: ['A camera using a MIPI CSI-2 data path. Record module compatibility, connector and lane assumptions alongside the link.', '使用 MIPI CSI-2 数据路径的摄像头。记录模块兼容性、连接器及通道数假设。'],
  depthcam: ['A camera providing depth information. Describe its host connection and how depth data is consumed by the perception pipeline.', '提供深度信息的摄像头。说明主机连接及感知流水线如何使用深度数据。'],
  servobus: ['A servo controlled through a serial bus. Show the bus chain and assign addresses or IDs according to the actual device.', '通过串行总线控制的舵机。显示总线链，并按实际设备分配地址或 ID。'],
  motorctl: ['A separate motor-control board. Use it when the driver, power stage and communication interface need their own architectural block.', '独立电机控制板。驱动器、功率级与通信接口需要独立架构模块时使用。'],
  vbat: ['A vehicle supply source. Record the nominal rail and operating limits rather than assuming every vehicle uses the same voltage.', '车辆供电源。记录标称电压与工作范围，不要假定所有车辆使用同一电压。'],
  fusebox: ['A protected power-distribution point. Label the branches and ratings, and connect loads through the intended protection path.', '带保护的配电点。标明支路和额定值，通过预定保护路径连接负载。'],
  obd: ['A vehicle diagnostic connector. Identify the diagnostic bus and connector assumptions used by the attached device.', '车辆诊断连接器。说明接入设备使用的诊断总线与连接器假设。'],
  lin: ['A LIN transceiver for a local vehicle subnetwork. Name the network and document its controller and device roles.', '车辆本地子网的 LIN 收发器。命名网络并记录控制器与设备角色。'],
  hbridge: ['A bidirectional motor-drive power stage. Show supply, control and load paths and record switching and current limits.', '双向电机驱动功率级。显示供电、控制与负载路径，记录开关及电流限制。'],
  wheelspeed: ['Wheel rotation or speed sensing. Identify the wheel and signal type, then connect the measurement to its controller.', '车轮旋转或速度测量。标明车轮与信号类型，再连接到控制器。'],
  autosoc: ['A vehicle application processor. Use it for domain or central compute, with explicit camera, network and power interfaces.', '车辆应用处理器。用于域控制或中央计算，明确摄像头、网络及供电接口。'],
  adas: ['An assistance-system processing block. Describe its sensing inputs, processing role and outputs; the diagram does not validate driving functions.', '辅助系统处理模块。描述感知输入、处理角色和输出；图纸不会验证驾驶功能。'],
  frontcam: ['A forward-facing vehicle camera. Label its position and image link, including serializer or cable assumptions where relevant.', '前向车载摄像头。标明位置与图像链路，必要时说明串行器或线缆假设。'],
  radar: ['A millimeter-wave radar sensing block. Record the module, host interface and the object or range data it supplies.', '毫米波雷达感知模块。记录模块、主机接口以及其提供的目标或距离数据。'],
  t1switch: ['An automotive Ethernet switch. Use it to fan out T1 links and record the speed and port expectations for each connection.', '车载以太网交换机。用于连接多个 T1 链路，并记录各连接的速率与端口要求。'],
  vgateway: ['A gateway between vehicle networks or domains. Name each network and document any protocol conversion or filtering role.', '车辆网络或域之间的网关。命名各网络，记录协议转换或过滤职责。'],
  cloud: ['An external cloud service or MQTT broker. Label the service and data exchanged; use fields or notes for the actual endpoint.', '外部云服务或 MQTT 消息代理。标明服务及交换数据，在字段或备注中记录实际端点。'],
  server: ['A server-side application or compute service. Give it a specific role such as telemetry, API or media processing.', '服务端应用或计算服务。指定具体角色，如遥测、API 或媒体处理。'],
  database: ['Persistent data storage. Describe the stored information and connect the services that read or write it.', '持久化数据存储。描述存储内容，并连接读写这些数据的服务。'],
  gateway: ['An edge device connecting local equipment to upstream services. Show both the local collection side and the uplink.', '将本地设备连接到上游服务的边缘设备。显示本地采集侧与上行链路。'],
  mobile: ['A mobile application or user-facing client. Connect it to the device or service it controls and describe the interaction.', '移动应用或面向用户的客户端。连接其控制的设备或服务，并说明交互。'],
  hostpc: ['A desktop or laptop used for development, operation or supervision. Label its role and the physical or network connection.', '用于开发、操作或监控的台式机、笔记本。标明角色及物理或网络连接。'],
  internet: ['An external network boundary. Use it to show where traffic leaves the local system and label the relevant connection.', '外部网络边界。用于表示流量离开本地系统的位置，并标明相关连接。'],
  accesspoint: ['A wireless access point joining clients to a network. Record its network role, uplink and relevant address information.', '将无线客户端接入网络的接入点。记录网络角色、上行链路与相关地址。'],
  router: ['Routes traffic between networks. Label the connected networks and record addressing or routing assumptions.', '在网络之间转发流量。标明所连接网络，并记录地址或路由假设。'],
  switch: ['Connects devices within a network segment. Describe port roles and VLAN or uplink assumptions in its fields and notes.', '连接同一网段内的设备。在字段和备注中描述端口角色、VLAN 或上行链路假设。'],
  asn: ['An autonomous-system boundary for network diagrams. Enter the AS identifier and connect its external relationships.', '网络图中的自治系统边界。填写 AS 标识并连接其外部关系。'],
  ipaddress: ['A specific network address or endpoint. Enter the address and use relationship links to show ownership or connectivity.', '具体网络地址或端点。填写地址，并用关系连线表示归属或连接关系。'],
  firewall: ['A network-policy enforcement point. Show the trust boundaries it separates and document intended allowed traffic.', '执行网络策略的节点。显示其分隔的信任边界，并记录允许通过的流量。'],
  waf: ['A web application firewall in an HTTP service path. Place it before the protected application and describe its filtering role.', 'HTTP 服务路径中的 Web 应用防火墙。放在被保护应用之前，说明过滤职责。'],
  proxy: ['An intermediary forwarding requests. State whether it serves clients or upstream services and show both sides.', '转发请求的中间节点。说明它服务于客户端还是上游服务，并显示两侧连接。'],
  cdn: ['A content-delivery edge. Connect users, edge delivery and origin services and describe what is cached.', '内容分发边缘节点。连接用户、边缘分发与源站，说明缓存内容。'],
  loadbalancer: ['Distributes requests among backends. Show the incoming service and each backend pool or destination.', '在后端之间分配请求。显示入口服务及各后端池或目标。'],
  apigateway: ['An API entry point handling routing and related policies. Label the public API and the internal services it reaches.', '处理路由及相关策略的 API 入口。标明公开 API 与其访问的内部服务。'],
  startend: ['Marks the beginning or end of a process. Name the trigger or final outcome and connect it with Flow links.', '标记流程的开始或结束。命名触发条件或最终结果，并用流程连线连接。'],
  process: ['One action or transformation in a workflow. Use a short verb phrase and connect the preceding and following steps.', '工作流中的一个动作或转换。使用简短动词短语，连接前后步骤。'],
  decision: ['A branching condition. Write the question in the diamond and label outgoing links with outcomes such as Yes and No.', '分支条件。在菱形内写出问题，为输出连线标明“是”“否”等结果。'],
  dataio: ['Data entering or leaving a process. Name the input or output and identify the producing or consuming step.', '进入或离开流程的数据。命名输入、输出，并标明产生或使用数据的步骤。'],
  document: ['A document produced or used by a workflow. Label the artifact and connect it to the relevant actions.', '工作流产生或使用的文档。标明文档，并连接相关动作。'],
  predefined: ['A named reusable subprocess. Use it to keep the overview readable and explain its internal steps elsewhere.', '命名的可复用子流程。用于保持总览清晰，内部步骤可在其他位置说明。'],
  preparation: ['An initialization or setup step. Describe what must be ready before the next action begins.', '初始化或准备步骤。说明下一个动作开始前必须具备的条件。'],
  manualinput: ['Information entered by a person. State what is entered and connect it to the step that uses it.', '人工输入的信息。说明输入内容，并连接使用该信息的步骤。'],
  delay: ['A waiting period or timing gate. Record the wait condition or duration and the action that resumes afterward.', '等待阶段或时间门槛。记录等待条件或时长，以及恢复后执行的动作。'],
  connector: ['A continuation marker for a busy flowchart. Give matching markers consistent labels so readers can follow the path.', '复杂流程图中的延续标记。为对应标记使用一致标签，方便读者跟踪路径。'],
  threatactor: ['An adversary or threat source in a threat model. Record the actor type, motivation and related targets.', '威胁模型中的对手或威胁来源。记录行为者类型、动机及相关目标。'],
  insider: ['Risk associated with trusted access inside the organization. Describe the access and whether the scenario is accidental, malicious or compromised.', '组织内部可信访问带来的风险。描述访问权限及误操作、恶意行为或账户失陷等情景。'],
  malware: ['Malicious software in a threat scenario. Record its type and connect delivery, affected systems and control relationships.', '威胁情景中的恶意软件。记录类型，连接投递路径、受影响系统及控制关系。'],
  ransomware: ['A ransomware scenario affecting systems or data. Identify the affected assets and document the recovery assumptions.', '影响系统或数据的勒索软件情景。标明受影响资产并记录恢复假设。'],
  botnet: ['A group of compromised devices under coordinated control. Show its command relationship and targets.', '受协调控制的一组失陷设备。显示指挥关系与目标。'],
  phishing: ['A deceptive message or interaction used to gain access. Connect the delivery channel, recipient and intended compromise.', '用于获取访问权限的欺骗信息或交互。连接投递渠道、接收者与预期失陷结果。'],
  c2: ['A command-and-control endpoint. Link it to controlled systems and describe the communication channel.', '命令与控制端点。连接被控系统，并说明通信渠道。'],
  vulnerability: ['A weakness in a system or component. Record the identifier and evidence, then link affected assets and relevant exploit scenarios.', '系统或组件的弱点。记录标识与证据，并连接受影响资产和相关利用情景。'],
  misconfig: ['An unsafe or unintended configuration. Describe the setting and its impact, and link the affected component.', '不安全或非预期配置。说明设置及其影响，并连接受影响组件。'],
  exploit: ['An exploitation step in a threat model. State the prerequisite weakness and resulting access or effect.', '威胁模型中的利用步骤。说明前提弱点及产生的访问权限或影响。'],
  supplychain: ['Compromise introduced through a supplier, dependency or update. Trace the entry point and the downstream affected assets.', '通过供应商、依赖或更新引入的失陷。跟踪入口及下游受影响资产。'],
  ddos: ['Traffic exhaustion or service-denial pressure. Show the traffic source, targeted service and relevant protective boundaries.', '流量耗尽或拒绝服务压力。显示流量来源、目标服务及相关防护边界。'],
  mitm: ['An adversary on a communication path. Place it between endpoints and describe the trust or transport weakness.', '位于通信路径上的对手。放在端点之间，并说明信任或传输层弱点。'],
  spoofing: ['False sensor data or impersonated measurements. Identify the sensor path and the decision that could be affected.', '虚假传感器数据或伪造测量。标明传感器路径及可能受影响的决策。'],
  credential: ['Compromised authentication material. Link it to the identity and systems it may expose; do not put real secrets into the diagram.', '失陷的身份验证材料。连接相关身份与可能暴露的系统；不要在图中填写真实密钥。'],
  dataleak: ['Unauthorized data leaving a system. Identify the data source, transfer path and destination in the scenario.', '未经授权离开系统的数据。标明情景中的数据来源、传输路径与目的地。'],
  physical: ['Physical interference with equipment. Describe the access point, affected hardware and resulting risk.', '对设备的物理干预。描述接触位置、受影响硬件及产生的风险。'],
  eeprom: ['Nonvolatile memory for configuration, firmware or data. Record the device and connect its storage interface and supply.', '用于配置、固件或数据的非易失存储器。记录设备并连接存储接口与电源。'],
  sdcard: ['Removable storage. Identify its role and the host interface, and record any capacity or endurance assumptions.', '可移除存储。标明用途与主机接口，并记录容量或耐久性假设。'],
  rtc: ['A real-time clock maintaining date or time. Connect the host bus and document backup power if the design uses it.', '维持日期或时间的实时时钟。连接主机总线；设计使用备用电源时应记录。'],
  crystal: ['A frequency reference or oscillator source. Label the frequency and the device using it; document loading details in notes.', '频率参考或振荡源。标明频率与使用设备，在备注中记录负载细节。'],
  debug: ['A programming or diagnostic connection. Record the debug standard, connector and target device.', '编程或诊断连接。记录调试标准、连接器及目标设备。'],
  ic: ['A general integrated circuit. Rename it to its function and customize ports before treating it as a specific component.', '通用集成电路。按功能重命名并自定义端口后，再用它表示具体组件。'],
  header: ['A pin header or connector boundary. Label the connector and document its pin mapping and electrical roles.', '排针或连接器边界。标明连接器，记录引脚映射及电气角色。'],
  testpoint: ['An accessible measurement point. Name the observed signal and connect it to the corresponding path.', '可接触的测量点。命名被测信号，并连接对应路径。'],
  fuse: ['An overcurrent-protection component. Place it in the intended supply path and record its actual rating.', '过流保护组件。放在预定供电路径中，并记录实际额定值。'],
  generic: ['A free-form architectural block for anything not covered by the catalogue. Rename it, add notes and use Customize to define meaningful ports.', '表示目录未覆盖内容的自由架构模块。重命名、添加备注，并通过自定义定义有意义的端口。'],
};
